DO $$ BEGIN
 CREATE TYPE "public"."auction_status" AS ENUM('Closed', 'Live');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "auctions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auctions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256),
	"description" text NOT NULL,
	"estimate" text NOT NULL,
	"highest_bid" integer NOT NULL,
	"deadline" timestamp with time zone NOT NULL,
	"auction_status" "auction_status" DEFAULT 'Live' NOT NULL,
	"imageurl" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "title_idx" ON "auctions" USING btree ("title");