import Head from 'next/head';
import { Hero } from '@/modules/home/components/hero';
import { GetStarted } from '@/modules/home/components/get-started';
import { ReactLenis } from 'lenis/react';

const Page = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" font-[family-name:var(--font-ibm-plex-sans)]">
        <ReactLenis root options={{ lerp: 0.08 }}>
          <div className="h-full mt-[70px]">
            <Hero />
            <GetStarted />
          </div>
        </ReactLenis>
      </main>
    </>
  );
};

export default Page;
